# Model parameters
embedding_dim: 64
num_layers: 3
num_layers_ie: 3
num_layers_mlp: 2

# Loss weights
lambda_u: 1.0
lambda_p: 1.0
lambda_c: 0.01

# Training parameters
num_pretrain_epochs: 100
unlearn_ratio: 0.05
fine_tune: true
fine_tune_epochs: 3
learning_rate: 0.001
batch_size: 512

# Dataset parameters
test_ratio: 0.2